-- Catálogo de estoque da TRIDI (empresa_id=1) importado do Sistema de Custos.
-- Componentes-peças, peças e produtos com CUSTO (visível só p/ admin no app).
-- Filtrado só p/ Tridi, deduplicado por (lower(nome), tipo). Rode no Supabase NOVO.

alter table public.estoque_itens add column if not exists custo numeric(12,2);
comment on column public.estoque_itens.custo is 'Custo unitário (R$). Exibido apenas para admin no app.';

create unique index if not exists estoque_itens_nome_tipo_uidx
  on public.estoque_itens (lower(nome), tipo);

insert into public.estoque_itens (nome, tipo, categoria, imagem_url, unidade, custo) values
('Acolchoado 11', 'componente', 'Almofadas', null, 'un', 0.3),
('Acolchoado 16', 'componente', 'Almofadas', null, 'un', 0.64),
('Acolchoado 6', 'componente', 'Almofadas', null, 'un', 0.16),
('Acolchoado almofada 22', 'componente', 'Almofadas', null, 'un', 1),
('Base da estrutura porta medalhas', 'componente', null, 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774437950999.png', 'un', 1.67),
('Bolacha Superior', 'componente', 'Chancelas', null, 'un', 0.14),
('Bolinha Puxador', 'componente', 'Carimbos', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1772461399503.jpg', 'un', 0.02),
('Circulo Alavanca', 'componente', 'Chancelas', null, 'un', 0.03),
('Espassador círcular porta medalha', 'componente', null, 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774381837373.png', 'un', 0.02),
('Estrutura Alavanca', 'componente', 'Chancelas', null, 'un', 0),
('Frente logo iluminada 35cm', 'componente', 'Logo Iluminada', null, 'un', 1.39),
('Frente logo iluminada 45cm', 'componente', 'Logo Iluminada', null, 'un', 2.23),
('Frente logo iluminada 60cm', 'componente', 'Logo Iluminada', null, 'un', 1.1),
('Frente MDF 3mm', 'componente', 'Logo Iluminada', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774442756718.png', 'un', 0.84),
('Fundo 11', 'componente', 'Almofadas', null, 'un', 0.16),
('Fundo 16', 'componente', 'Almofadas', null, 'un', 0.32),
('Fundo 6', 'componente', null, null, 'un', 0.06),
('Fundo estrutura logo 25cm', 'componente', 'Logo Iluminada', null, 'un', 0.85),
('Fundo estrutura logo 35cm', 'componente', 'Logo Iluminada', null, 'un', 1.39),
('Fundo estrutura logo 45cm', 'componente', 'Logo Iluminada', null, 'un', 2.23),
('Fundo estrutura logo 60cm', 'componente', 'Logo Iluminada', null, 'un', 3.99),
('Fundo MDF 3mm', 'componente', 'Logo Iluminada', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774442478662.png', 'un', 0.84),
('Guia Alavanca', 'componente', 'Chancelas', null, 'un', 0.01),
('Lateral Costa 11', 'componente', 'Almofadas', null, 'un', 0.02),
('Lateral Costa 16', 'componente', 'Almofadas', null, 'un', 0.04),
('Lateral Costa 6', 'componente', 'Almofadas', null, 'un', 0.02),
('Lateral costa almofada 22', 'componente', 'Almofadas', null, 'un', 0.03),
('Lateral estrutura logo 25cm', 'componente', 'Logo Iluminada', null, 'un', 0.11),
('Lateral estrutura logo 35cm', 'componente', 'Logo Iluminada', null, 'un', 0.13),
('Lateral estrutura logo 45cm', 'componente', 'Logo Iluminada', null, 'un', 0.59),
('Lateral estrutura logo 60cm', 'componente', 'Logo Iluminada', null, 'un', 1.1),
('Lateral Frente 11', 'componente', 'Almofadas', null, 'un', 0.03),
('Lateral Frente 16', 'componente', 'Almofadas', null, 'un', 0.04),
('Lateral Frente 6', 'componente', 'Almofadas', null, 'un', 0.02),
('Lateral frente almofada 22', 'componente', 'Almofadas', null, 'un', 0.06),
('Lateral Rolamento 11', 'componente', 'Almofadas', null, 'un', 0.03),
('Lateral Rolamento 16', 'componente', 'Almofadas', null, 'un', 0.04),
('Lateral Rolamento 6', 'componente', 'Almofadas', null, 'un', 0.02),
('Lateral Rolamento almofada 22', 'componente', 'Almofadas', null, 'un', 0.06),
('Parede Base', 'componente', 'Chancelas', null, 'un', 0.37),
('Parte de cima estrutura logo 25cm', 'componente', 'Logo Iluminada', null, 'un', 0.93),
('Pinça Inferior', 'componente', 'Chancelas', null, 'un', 0.2),
('Pinça Superior', 'componente', 'Chancelas', null, 'un', 0),
('PS Acabamento', 'componente', 'Chancelas', null, 'un', 0.17),
('PS Circulo Alavanca', 'componente', 'Chancelas', null, 'un', 0.02),
('PS Preto Logo 25cm', 'componente', 'Logo Iluminada', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774443387454.png', 'un', 1.1),
('PS Preto Logo 35cm', 'componente', 'Logo Iluminada', null, 'un', 1.83),
('PS Preto Logo 45cm', 'componente', 'Logo Iluminada', null, 'un', 2.94),
('PS Preto Logo 60cm', 'componente', 'Logo Iluminada', null, 'un', 5.75),
('PS Translucido', 'componente', 'Logo Iluminada', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774443265943.png', 'un', 4.16),
('PS Translucido logo 25cm', 'componente', 'Logo Iluminada', null, 'un', 4.17),
('PS Translucido logo 35cm', 'componente', 'Logo Iluminada', null, 'un', 6.94),
('PS Translucido logo 45cm', 'componente', 'Logo Iluminada', null, 'un', 11.14),
('PS Translucido logo 60cm', 'componente', 'Logo Iluminada', null, 'un', 19.8),
('Puxador Femea', 'componente', 'Carimbos', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1772469523095.jpg', 'un', 0.02),
('Puxador Macho', 'componente', 'Carimbos', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1772469497654.jpg', 'un', 0.02),
('Reforço Inferior', 'componente', 'Chancelas', null, 'un', 0.1),
('Trava Clichê', 'componente', 'Chancelas', null, 'un', 0.01),
('Trava estrura logo 25cm', 'componente', 'Logo Iluminada', null, 'un', 0.02),
('Trava estrutura logo 35cm', 'componente', null, null, 'un', 0.01),
('Trava estrutura logo 60cm', 'componente', 'Logo Iluminada', null, 'un', 0.01),
('Trava logo 25cm - MDF 3mm', 'componente', 'Logo Iluminada', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/componentes_pecas/1774443006222.png', 'un', 0.78),
('Trava logo iluminada 45cm', 'componente', 'Logo Iluminada', null, 'un', 0.01),
('Travas', 'componente', 'Chancelas', null, 'un', 0.03),
('Acrílico 3cm', 'peca', 'Carimbos', null, 'un', 0.12),
('Acrílico 4cm', 'peca', 'Carimbos', null, 'un', 0.22),
('Acrílico 5cm', 'peca', 'Carimbos', null, 'un', 0.33),
('Acrilico Chan. 4cm', 'peca', 'Chancelas', null, 'un', 0.22),
('Acrilico Chan. 5cm', 'peca', 'Chancelas', null, 'un', 0.33),
('Alavanca', 'peca', 'Chancelas', null, 'un', 2.17),
('Amortecedor Carimbo 10cm', 'peca', 'Carimbos', null, 'un', 1.58),
('Amortecedor Carimbo 11cm', 'peca', 'Carimbos', null, 'un', 1.88),
('Amortecedor Carimbo 12cm', 'peca', 'Carimbos', null, 'un', 2.23),
('Amortecedor Carimbo 13cm', 'peca', 'Carimbos', null, 'un', 2.58),
('Amortecedor Carimbo 14cm', 'peca', 'Carimbos', null, 'un', 2.97),
('Amortecedor Carimbo 15cm', 'peca', 'Carimbos', null, 'un', 3.41),
('Amortecedor Carimbo 4cm', 'peca', 'Carimbos', null, 'un', 0.32),
('Amortecedor Carimbo 5cm', 'peca', 'Carimbos', null, 'un', 0.45),
('Amortecedor Carimbo 6cm', 'peca', 'Carimbos', null, 'un', 0.62),
('Amortecedor Carimbo 7cm', 'peca', 'Carimbos', null, 'un', 0.83),
('Amortecedor Carimbo 8cm', 'peca', 'Carimbos', null, 'un', 1.03),
('Amortecedor Carimbo 9cm', 'peca', 'Carimbos', null, 'un', 1.31),
('Base 11', 'peca', 'Almofadas', null, 'un', 1.29),
('Base 16', 'peca', 'Almofadas', null, 'un', 2.27),
('Base 6', 'peca', 'Almofadas', null, 'un', 1.45),
('Base Acrílico 3cm', 'peca', 'Carimbos', null, 'un', 0.03),
('Base Acrílico 4cm', 'peca', 'Carimbos', null, 'un', 0.05),
('Base Acrílico 5cm', 'peca', 'Carimbos', null, 'un', 0.07),
('Base almofada 22', 'peca', 'Almofadas', null, 'un', 1.64),
('Base Carimbo 10cm', 'peca', 'Carimbos', null, 'un', 0.31),
('Base Carimbo 11cm', 'peca', 'Carimbos', null, 'un', 0.37),
('Base Carimbo 12cm', 'peca', 'Carimbos', null, 'un', 0.43),
('Base Carimbo 13cm', 'peca', 'Carimbos', null, 'un', 0.5),
('Base Carimbo 14cm', 'peca', 'Carimbos', null, 'un', 0.57),
('Base Carimbo 15cm', 'peca', 'Carimbos', null, 'un', 0.65),
('Base Carimbo 4cm', 'peca', 'Carimbos', null, 'un', 0.07),
('Base Carimbo 5cm', 'peca', 'Carimbos', null, 'un', 0.07),
('Base Carimbo 6cm', 'peca', 'Carimbos', null, 'un', 0.13),
('Base Carimbo 7cm', 'peca', 'Carimbos', null, 'un', 0.17),
('Base Carimbo 8cm', 'peca', 'Carimbos', null, 'un', 0.21),
('Base Carimbo 9cm', 'peca', 'Carimbos', null, 'un', 0.26),
('Base carimbo decorativo', 'peca', 'Carimbos', null, 'un', 0.04),
('Borracha 10cm', 'peca', 'Carimbos', null, 'un', 1.48),
('Borracha 11cm', 'peca', 'Carimbos', null, 'un', 1.79),
('Borracha 12cm', 'peca', 'Carimbos', null, 'un', 2.13),
('Borracha 13cm', 'peca', 'Carimbos', null, 'un', 2.49),
('Borracha 14cm', 'peca', 'Carimbos', null, 'un', 2.89),
('Borracha 15cm', 'peca', 'Carimbos', null, 'un', 3.32),
('Borracha 4cm', 'peca', 'Carimbos', null, 'un', 0.24),
('Borracha 5cm', 'peca', 'Carimbos', null, 'un', 0.37),
('Borracha 6cm', 'peca', 'Carimbos', null, 'un', 0.54),
('Borracha 7cm', 'peca', 'Carimbos', null, 'un', 0.73),
('Borracha 8cm', 'peca', 'Carimbos', null, 'un', 0.95),
('Borracha 9cm', 'peca', 'Carimbos', null, 'un', 1.2),
('Borracha decorativo', 'peca', 'Carimbos', null, 'un', 0.08),
('Clichê', 'peca', 'Chancelas', null, 'un', 0.44),
('Corpo Base', 'peca', 'Chancelas', null, 'un', 4.4),
('espaçador circular 25mm', 'peca', 'Organizadores', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/pecas/1774375747959.png', 'un', 0.02),
('Estrutura logo 25cm', 'peca', 'Logo Iluminada', null, 'un', 16.42),
('Estrutura logo 35cm', 'peca', 'Logo Iluminada', null, 'un', 38.87),
('Estrutura logo 45cm', 'peca', 'Logo Iluminada', null, 'un', 43.37),
('Estrutura logo 60cm', 'peca', 'Logo Iluminada', null, 'un', 50.37),
('Estrutura porta medalha', 'peca', 'Organizadores', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/pecas/1774455086307.png', 'un', 1.85),
('Fundo luminaria 25cm', 'peca', 'Almofadas', null, 'un', 0.81),
('Pézinho Almofada', 'peca', 'Almofadas', null, 'un', 0.02),
('Puxador', 'peca', 'Carimbos', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/pecas/1772469656112.jpg', 'un', 0.78),
('Tampa 11', 'peca', 'Almofadas', null, 'un', 0.35),
('Tampa 16', 'peca', 'Almofadas', null, 'un', 0.77),
('Tampa 6', 'peca', 'Almofadas', null, 'un', 0.12),
('Tampa almofada 22', 'peca', 'Almofadas', null, 'un', 1.18),
('Tampa logo 25cm', 'peca', 'Logo Iluminada', null, 'un', 9.28),
('Tampa logo 35cm', 'peca', 'Logo Iluminada', null, 'un', 12.11),
('Tampa logo 45cm', 'peca', 'Logo Iluminada', null, 'un', 19.29),
('Tampa logo 60cm', 'peca', 'Logo Iluminada', null, 'un', 30.98),
('Almofada 11', 'produto', 'Almofadas', null, 'un', 2.46),
('Almofada 16', 'produto', 'Almofadas', null, 'un', 3.86),
('Almofada 22x22', 'produto', 'Almofadas', null, 'un', 4.35),
('Almofada 6', 'produto', 'Almofadas', null, 'un', 2.39),
('Carimbo 10cm', 'produto', 'Carimbos', null, 'un', 5.58),
('Carimbo 11cm', 'produto', 'Carimbos', null, 'un', 6.4),
('Carimbo 12cm', 'produto', 'Carimbos', null, 'un', 7.29),
('Carimbo 13cm', 'produto', 'Carimbos', null, 'un', 8.21),
('Carimbo 14cm', 'produto', 'Carimbos', null, 'un', 9.22),
('Carimbo 15cm', 'produto', 'Carimbos', null, 'un', 10.31),
('Carimbo 4cm', 'produto', 'Carimbos', null, 'un', 2.13),
('Carimbo 5cm', 'produto', 'Carimbos', null, 'un', 2.39),
('Carimbo 6cm', 'produto', 'Carimbos', null, 'un', 2.15),
('Carimbo 7cm', 'produto', 'Carimbos', null, 'un', 3.52),
('Carimbo 8cm', 'produto', 'Carimbos', null, 'un', 4.12),
('Carimbo 9cm', 'produto', 'Carimbos', null, 'un', 4.84),
('Carimbo Acrílico 3cm', 'produto', 'Carimbos', null, 'un', 1.36),
('Carimbo Acrílico 4cm', 'produto', 'Carimbos', null, 'un', 1.63),
('Carimbo Acrílico 5cm', 'produto', 'Carimbos', null, 'un', 1.9),
('Carimbo Decorativo', 'produto', 'Carimbos', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/produtos/1777637827565.webp', 'un', 0.12),
('Chancela 4cm', 'produto', 'Chancelas', null, 'un', 8.56),
('Chancela 5cm', 'produto', 'Chancelas', null, 'un', 8.39),
('Logo iluminada 25cm', 'produto', 'Logo Iluminada', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/produtos/1774447729776.jpg', 'un', 27.94),
('Logo iluminada 35cm', 'produto', 'Logo Iluminada', null, 'un', 50.98),
('Logo iluminada 45cm', 'produto', 'Logo Iluminada', null, 'un', 62.66),
('Logo iluminada 60cm', 'produto', 'Logo Iluminada', null, 'un', 81.5),
('Porta medalhas 24 unidades', 'produto', 'Organizadores', 'https://cfganxuugrpfljirmerz.supabase.co/storage/v1/object/public/imagens/produtos/1774437940768.png', 'un', 2.89)
on conflict (lower(nome), tipo) do update
  set custo = excluded.custo,
      categoria = coalesce(excluded.categoria, public.estoque_itens.categoria),
      imagem_url = coalesce(public.estoque_itens.imagem_url, excluded.imagem_url),
      updated_at = now();
